
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "5672:5672" #puerto default de RabbitMQ
      - "15672:15672"  #interfaz de rabbitMQ
  

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest    
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr"]
      interval: 10s
      retries: 10
      start_period: 120s
      timeout: 10s
    volumes:
      - sqlserver_data:/var/opt/mssql

  inventoryservice:
    build:
      context: ./InventoryService
    container_name: publisher
    ports:
      - "8001:80"
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ProductDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development

  subscriber:
    build:
      context: ./NotificacionesService
    container_name: subscriber
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started        
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=NotificationDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
volumes:
  sqlserver_data:

  

  
